name: 'Deploy to Jamsocket'
description: 'This action will handle deploying session backend code to your Jamsocket service.'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get commit metadata
      id: commit_info
      run: |
        echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
        echo "GITHUB_ACCOUNT_NAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY_NAME=${{ github.repository }}" >> $GITHUB_ENV
