name: 'Publish to Jamsocket'
description: 'Build and publish a Docker image to Jamsocket registry'
inputs:
  JAMSOCKET_API_TOKEN:
    description: 'Token for Jamsocket authentication'
    required: true
  IMAGE_NAME:
    description: 'Name of the Docker image (ACCOUNT_NAME/SERVICE_NAME)'
    required: true
  DOCKER_BUILD_CONTEXT:
    description: 'Path to the Docker build context'
    required: true
    default: '.'
  DOCKERFILE_PATH:
    description: 'Path to the Dockerfile'
    required: true
    default: './Dockerfile'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Inputs
      shell: bash
      run: |
        echo "JAMSOCKET_API_TOKEN: ${{ inputs.JAMSOCKET_API_TOKEN }}"
        echo "IMAGE_NAME: ${{ inputs.IMAGE_NAME }}"
        echo "DOCKER_BUILD_CONTEXT: ${{ inputs.DOCKER_BUILD_CONTEXT }}"
        echo "DOCKERFILE_PATH: ${{ inputs.DOCKERFILE_PATH }}"

  - name: Set JAMCR_USER from token
      shell: bash
      run: |
        JAMSOCKET_API_TOKEN=${{ inputs.JAMSOCKET_API_TOKEN }}
        JAMCR_USER="${JAMSOCKET_API_TOKEN%%.*}"
        echo "JAMCR_USER: $JAMCR_USER"
        echo "JAMCR_USER=${JAMCR_USER}" >> $GITHUB_ENV

    - name: Set JAMCR_PASS from token
      shell: bash
      run: |
        JAMSOCKET_API_TOKEN=${{ inputs.JAMSOCKET_API_TOKEN }}
        JAMCR_PASS="${JAMSOCKET_API_TOKEN#*.}"
        echo "JAMCR_PASS: $JAMCR_PASS"
        echo "JAMCR_PASS=${JAMCR_PASS}" >> $GITHUB_ENV
