name: Deploy to Jamsocket
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Jamsocket
        uses: jamsocket/jamsocket-deploy-action@v0.1.3
        with:
          jamsocket_api_token: ${{ secrets.JAMSOCKET_API_TOKEN }}
          jamsocket_account: felicia
          jamsocket_service: renaissance
          docker_build_context: ./server
          dockerfile_path: ./server/Dockerfile.jamsocket

# name: Test Publish to Jamsocket Action

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Get commit metadata
#         id: commit_info
#         run: |
#           echo "Commit Hash: ${{ github.sha }}"
#           echo "Commit Message: ${{ github.event.head_commit.message }}"
#           echo "BRANCH_NAME: ${{ github.ref_name }}"
#           echo "Respository: ${{ github.repository }}"
